.TH "ew::ErrorRuntime" 3 "4.20100927" "EW Library" "EW Library"
.ad l
.nh
.SH NAME
ew::ErrorRuntime \- 
.PP
Runtime Exception.  

\fBew::ErrorRuntime\fP is an exception thrown by EW library classes to report runtime errors.
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ew/ErrorRuntime.h>\fP
.PP
Inherits std::runtime_error.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBErrorRuntime\fP (const std::string &desc)"
.br
.in -1c
.SH DESCRIPTION
.PP 
.PP
\fBew::ErrorRuntime\fP is a trivial extension of std::runtime_error. 
.SH CONSTRUCTORS AND DESCTRUCTORS
.PP 
.SS "ew::ErrorRuntime::ErrorRuntime (const std::string & desc)\fC [explicit]\fP"Construct an EW::Error_Runtime object. 
.PP
\fBParameters:\fP
.RS 4
\fIdesc\fP the error description 
.RE
.PP


