#
# Make a version file that includes the FPL version and git revision
#
SET(ET_VERSION_MAJOR "1")
SET(ET_VERSION_MINOR "72")
SET(ET_VERSION_PATCH "0")

SET(ET_VERSION "${ET_VERSION_MAJOR}.${ET_VERSION_MINOR}.${ET_VERSION_PATCH}")
SET(ET_API_VERSION ${ET_VERSION_MAJOR}${ET_VERSION_MINOR})

#EXECUTE_PROCESS
#(
#    COMMAND git log -1 --format=%h
#    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
#    OUTPUT_VARIABLE GIT_COMMIT_HASH
#    OUTPUT_STRIP_TRAILING_WHITESPACE
#)

#CONFIGURE_FILE
#(
#    ${CMAKE_MODULE_PATH}/version.h.in
#    ${CMAKE_SOURCE_DIR}/src/version.h
#)
