@ECHO OFF
rem
rem This file is generated by the Qt installer
rem

echo Setting up a Qt environment...

set QTDIR=C:\Qt\4.8.5
echo -- QTDIR set to %QTDIR%

set PATH=%QTDIR%\bin;%PATH%
echo -- Added %QTDIR%\bin to PATH

REM set QMAKESPEC=G:\qt\qt-4.8.5\mkspecs\win32-g++
set QMAKESPEC=win32-g++
echo -- QMAKESPEC set to "win32-g++"

REM 
ECHO -- make sure your TDM GCC installation points to the correct directory by examining the PATH variable
set PATH=D:\TDM-GCC\TDM-GCC-32\bin;C:\strawberry-perl-5.18.1.1-32bit-portable\perl\bin;C:\Windows\system32;%PATH%

ECHO -- your current PATH is
ECHO. %PATH%


@ECHO ON