@echo off
rem
rem This file is generated by the Qt installer
rem

echo Setting up a Qt environment...

set QTDIR=C:\Qt\4.8.5
echo -- QTDIR set to %QTDIR%

set PATH=%QTDIR%\bin;%PATH%
echo -- Added %QTDIR%\bin to PATH

REM set QMAKESPEC=G:\qt\qt-4.8.5\mkspecs\win32-g++
set QMAKESPEC=win32-g++
echo -- QMAKESPEC set to "win32-g++"
